name: Python Integration Tests

on: 
   pull_request:
         branches:
            - main
jobs:
    test:
       runs-on: ubuntu-latest     

       steps:
           - users: actions/checkout@v3
           - name : Set up Python 
             users: actions/setup-python@v3
             with: 
                 python-version: '3.9'
           - name: Install Dependencies
             run: pip install unittest
           -name : Run Tests
            run: python -m unittest discover                